### ISSUE TITLE
don't started on my linux machine. 

### ISSUE THREAD

**Issue by vasiaplaton** [zst-embedded/STM32-LCD_Font_Generator#2]
>  $ python3 ../stm32-font.py --font Menlo.ttc --size 32
>   File "../stm32-font.py", line 43
>     return f'{array}, /* |{comment}| */\r\n'
>                                           ^
> SyntaxError: invalid syntax
> 
> 

> $ python3 --version
> Python 3.4.3

I don't changed anything in your code.

**Comment by vasiaplaton** [comment]
I have already add Menlo.ttc to example dir

**Comment by zst123** [comment]
The script requires **Python 3.6 and above**.

Could you try it with that?

**Comment by vasiaplaton** [comment]
Thank you. I try to start it with python3.6.8. Now i have another error. 

> $ python3.6 ../stm32-font.py --font Menlo.ttc --size 32
> Traceback (most recent call last):
>   File "../stm32-font.py", line 1, in <module>
>     from PIL import Image, ImageFont, ImageDraw
>   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 53, in <module>
>     from PIL import _imaging as core
> ImportError: cannot import name '_imaging'
> $ python3.6 --version
> Python 3.6.8

I googled. But nothing changed. 
> $  pip3 install Pillow
> Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (2.3.0)

**Comment by zst123** [comment]
Try it with pip3.6 for python3.6?

**Comment by vasiaplaton** [comment]
I use wirtualenv and python3.6. All work perfectly. Thank you.
